// import "./cubes";
// import "./scene";
// import "./material";
// import "./lights";
// import "./camera";
// import "./shadows";
// import "./fog";
// import "./render_targets";
// import "./demographic_data_2d_test";
// import "./lots_of_objects";
// import "./lots_of_objects_animated";
// import "./obj_file";
import "./gltf_file";
